name: CI

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      publish-lib:
        description: 'What lib to publish?'
        required: true
        type: choice
        options:
          - All
          - asserts
          - binderhelper
          - coroutines
          - logger
          - mic_camera_state
          - Messaging
          - AppState
          - CV
          - Camera

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
        
      - name: Run gradle publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
          PUBLISH_LIB: ${{ github.event.inputs.publish-lib }}
        run: >
          eval "$(./.github/workflows/publish.main.kts $PUBLISH_LIB)"
          --max-workers 1 
          -PossrhUsername="$OSSRH_USERNAME" 
          -PossrhPassword="$OSSRH_TOKEN" 
          -Psigning.key="$SIGNING_KEY_BASE64" 
          -Psigning.keyId="$SIGNING_KEY_ID" 
          -Psigning.password="$SIGNING_KEY_PASSPHRASE"
